print("WELCOME TO  MY BAND NAME SUGGESTION APP")
nickname = input("What is Your Nickname: ")
city = input("You Grew Up From What City?:")
hobby = input("Type Of Hobby: ")
print("Hello!" + nickname)
print("The Name Of The City You Grew Up From Is " + city)
print("Your Hobby is " + hobby )
print("Your Band Name Can Be,... " + nickname + city)
print("Thank You! " + nickname)
print("BYE.")
