print('HELLO!')
print('WELLCOME TO UNDISPUTED CALCULATOR')
print('pleasen enter your two digits')
first=input('Enter your first number:')
second=input('Enter your second number:')
print('ANS = ' + str ((int(first)+int(second))))
print('Goodbye!')
