print("WELCOME TO YOUR LIFE CALCULATOR")
print("An app which can be used to calculate the rest of your life in a week")
print("let's get started!:")
name=input("What's your name:")
age=input("How old are you:")
month=input("What month were you born? :")
week=input("What week of the month were you born? :")
day=input("What day of the month were you born? :")
hours=input("What hour, if you know? ")
guess=input(" How old do you want to live: ")
print(name)
#Print (" if you were to live for " + "you have exactly; ")
#print(str(int(guess)-int(age)) + " years to live ")
